import '../styles/globals.css'
import { Navbar } from './components/Navbar'
import { useState, useEffect } from "react"
import Head from 'next/head'
import { useRouter } from 'next/router';


function MyApp({ Component, pageProps }) {

  const [loader, setLoader] = useState(false)
  const [closeMenu, setCloseMenu] = useState(true)
  const { asPath, pathname } = useRouter();
  console.log(asPath); // '/blog/xyz'


  useEffect(() => {
    setTimeout(() => { setLoader(true) }, 1000);
  },[loader])

  return (
  <>
  <Head>
    <title>LS - PORTFOLIO</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/Logo.svg" />
  </Head>
  <main className='main-total' style={{background:`${asPath === "/" ? "#f4f9fc" : asPath === "/trabajos" ? "#FFF7F7" : null}`}}>
    <div className={`loader-real ${loader && "loader-off"}`} style={{background:`${asPath === "/" ? "#AADCEC" : asPath === "/trabajos" ? "#FCC5D3" : null}`}}>
      <div className={`wrapper ${loader && "loader-off-spans"}`}>
          <div className="circle"></div>
          <div className="circle"></div>
          <div className="circle"></div>
          <div className="shadow"></div>
          <div className="shadow"></div>
          <div className="shadow"></div>
          <span>Loading</span>
      </div>
    </div>
    {
      loader &&
      <>
        <Navbar setLoader={setLoader} setCloseMenu={setCloseMenu} closeMenu={closeMenu} asPath={asPath}/>
        {closeMenu && <Component {...pageProps} setLoader={setLoader}/>}
      </>
    }
    <small className="made-in-lautaro">
      © Lautaro Stein. 2022
    </small>
  </main>
  </>
  )
}

export default MyApp
