import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import {useEffect, useState} from "react"

export default function Home(props) {
  const [mouse, setMouse] = useState()
  useEffect(() => {
    setMouse({x:0, y:0})
  },[props])

  const onMouseMove = (e) => {
    setMouse({x: e.screenX * 0.002, y:e.screenY * 0.0065})
  }

  console.log(mouse)
  return (
    <>
      <Head>
        <title>Lautaro Stein</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section onMouseMove={onMouseMove.bind(this)} className='container-total-pages'>
        <div className='texto-contexto-pagina'>
          <h1>Hola, mi<br/>Nombre es <b>Lautaro</b></h1>
          <p>Soy <b>desarrollador FullStack MERN</b> que vive en <br/>Argentina en el sur provincia de Chubut.</p>
          <span className='span-animation-scroll'>
            <span>S</span>
            <span>C</span>
            <span>R</span>
            <span>O</span>
            <span>L</span>
            <span>L</span>
          </span>
        </div>
        {mouse &&<div className='imagen-fondo-yo' style={{transform: `translatex(${mouse.x * 1.5}px) translateY(${mouse.y * 2.5}px)`, transition: "all 1s"}}></div>}
        <img className="imagen-yo" src="/yo-1.svg" alt="Picture of the author" width={500} height={500} />
        {mouse &&<img className="imagen-yo-dos" src="/yo-2.svg" alt="Picture of the author" width={500} height={500} style={{transform: `translatex(${mouse.x}px) translateY(${mouse.y}px)`, transition: "all 1s"}}/>}
      </section>

      <footer>
      </footer>
    </>
  )
}
