import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import {useEffect, useState, useRef} from "react"

export default function Home(props) {

  const [mouse, setMouse] = useState()
  const [background, setBackground] = useState(false)

  const divRef = useRef()

  useEffect(()=>{
    const handleScroll = () => {
      const div = divRef.current;
      if(div){
        const { y } = div.getBoundingClientRect();
      }
        const backgroundColor = y <= 550 && true 
        setBackground(backgroundColor)
    }
    window.addEventListener('scroll', handleScroll)

    return () => {
      window.removeEventListener('scroll', handleScroll)
    }
  },[])



  useEffect(() => {
    setMouse({x:0, y:0})
  },[props])

  const onMouseMove = (e) => {
    setMouse({x: e.screenX * 0.002, y:e.screenY * 0.005})
  }

  return (
    <>
      <Head>
        <title>Lautaro Stein</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='div-section-main'>
        <section onMouseMove={onMouseMove.bind(this)} className='container-total-pages'>
          <div className='texto-contexto-pagina'>
            <h1>Hola, mi<br/>Nombre es <b>Lautaro</b></h1>
            <p>Mi pasion <b>desarrollador FullStack MERN</b> vivo en <br/>Argentina en el sur, provincia de Chubut.</p>
            <span className='span-animation-scroll'>
              <span>S</span>
              <span>C</span>
              <span>R</span>
              <span>O</span>
              <span>L</span>
              <span>L</span>
            </span>
          </div>
          {mouse &&<div className='imagen-fondo-yo' style={{transform: `translatex(${mouse.x * 2}px) translateY(${mouse.y * 5}px)`, transition: "all 1s"}}></div>}
          <img className="imagen-yo" src="/yo-1.svg" alt="Picture of the author" width={500} height={500} />
          {mouse &&<img className="imagen-yo-dos" src="/yo-2.svg" alt="Picture of the author" width={500} height={500} style={{transform: `translatex(${mouse.x}px) translateY(${mouse.y}px)`, transition: "all 1s"}}/>}
        </section>
        <div ref={divRef} style={{height:"500px"}} className='working-index'>
          {
            background &&
            <h2>Trabajemos Juntos.</h2>
          }
        </div>
      </div>
    </>
  )
}
