import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Navbar } from './components/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Lautaro Stein</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main-total'>
        <Navbar />
        
      </main>

      <footer>
      </footer>
    </>
  )
}
